const translations: Record<string, { title: string; summary: string; details: string }> = {
  en: {
    title: "FSP Privacy Policy",
    summary: "FSP can be played offline without an account. This policy explains what is processed when you choose online account, squad, matchmaking and voice features.",
    details: `<section><h2>Data we process</h2><p>If you create an account, we process your email address, account and player identifiers, display name, selected appearance, squad membership, matchmaking and room state, match progress and security/session information. Our hosting providers may also process technical data such as IP address, request time and diagnostic logs.</p></section><section><h2>How data is used</h2><p>Data is used to authenticate accounts, synchronize profiles, find matches, operate squads, prevent abuse, keep matches consistent, provide support and maintain service security. We do not sell personal data.</p></section><section><h2>Microphone and squad voice</h2><p>Squad voice requests microphone permission only when an eligible signed-in squad member starts voice in a match. Push-to-talk begins muted. Audio is relayed for live communication through the voice provider and is not intentionally recorded by FSP.</p></section><section><h2>Service providers</h2><p>FSP uses Supabase for account, database and server-function services, and Cloudflare for match relay and live voice infrastructure. These providers process data only as needed to deliver their services and under their own security and privacy terms.</p></section><section><h2>Retention and deletion</h2><p>Offline settings remain on your device until you clear app data or uninstall. Account data is retained while your account is active or as required for security and legal obligations. You can permanently delete the account and associated game data from Settings → Account &amp; Privacy. You can also use the external deletion request link below.</p></section><section><h2>Security and children</h2><p>We use access controls and encrypted network connections, but no online system can guarantee absolute security. FSP is not directed to children under 13. Contact us if you believe a child provided personal data.</p></section><section><h2>Your choices</h2><p>You may play offline, deny microphone permission, disable music or effects, sign out, or request account deletion. Contact us for privacy questions or requests that cannot be completed in the app.</p></section>`,
  },
  ar: {
    title: "سياسة خصوصية FSP",
    summary: "يمكن لعب FSP دون اتصال وبدون حساب. توضح هذه السياسة ما تتم معالجته عند اختيار الحساب والفرق والبحث عن المباريات والصوت عبر الإنترنت.",
    details: `<section><h2>البيانات التي نعالجها</h2><p>إذا أنشأت حسابًا، نعالج البريد الإلكتروني ومعرّفات الحساب واللاعب واسم العرض والمظهر المختار وعضوية الفريق وحالة البحث والغرفة وتقدم المباريات ومعلومات الجلسة والأمان. وقد يعالج مزودو الاستضافة أيضًا بيانات تقنية مثل عنوان IP ووقت الطلب وسجلات التشخيص.</p></section><section><h2>كيفية استخدام البيانات</h2><p>تُستخدم البيانات لتسجيل الدخول ومزامنة الملف الشخصي والبحث عن المباريات وتشغيل الفرق ومنع إساءة الاستخدام والحفاظ على اتساق المباراة وتقديم الدعم وأمان الخدمة. لا نبيع البيانات الشخصية.</p></section><section><h2>الميكروفون وصوت الفريق</h2><p>يُطلب إذن الميكروفون فقط عندما يبدأ عضو مسجل في فريق مؤهل ميزة الصوت داخل المباراة. يبدأ الضغط للتحدث في وضع الكتم. يُنقل الصوت للاتصال المباشر عبر مزود خدمة الصوت ولا تسجله FSP عمدًا.</p></section><section><h2>مزودو الخدمة</h2><p>تستخدم FSP خدمة Supabase للحسابات وقاعدة البيانات ووظائف الخادم، وخدمة Cloudflare لترحيل المباريات والبنية التحتية للصوت المباشر. يعالج هؤلاء المزودون البيانات بالقدر اللازم لتقديم خدماتهم ووفق شروط الأمان والخصوصية الخاصة بهم.</p></section><section><h2>الاحتفاظ والحذف</h2><p>تبقى الإعدادات المحلية على جهازك حتى مسح بيانات التطبيق أو إزالته. تُحتفظ بيانات الحساب أثناء نشاطه أو حسب متطلبات الأمان والقانون. يمكنك حذف الحساب وبيانات اللعبة المرتبطة به نهائيًا من الإعدادات ← الحساب والخصوصية، أو استخدام رابط طلب الحذف الخارجي أدناه.</p></section><section><h2>الأمان والأطفال</h2><p>نستخدم ضوابط وصول واتصالات شبكة مشفرة، لكن لا يمكن ضمان الأمان المطلق لأي نظام متصل. اللعبة غير موجهة للأطفال دون 13 عامًا. تواصل معنا إذا اعتقدت أن طفلًا قدم بيانات شخصية.</p></section><section><h2>اختياراتك</h2><p>يمكنك اللعب دون اتصال أو رفض إذن الميكروفون أو تعطيل الموسيقى والمؤثرات أو تسجيل الخروج أو طلب حذف الحساب. تواصل معنا لطلبات الخصوصية التي يتعذر تنفيذها داخل اللعبة.</p></section>`,
  },
};

Deno.serve((request) => {
  if (request.method !== "GET") return new Response("Method not allowed", { status: 405 });
  const url = new URL(request.url);
  const language = url.searchParams.get("lang")?.toLowerCase() === "ar" ? "ar" : "en";
  const content = translations[language];
  const supportEmail = Deno.env.get("FSP_SUPPORT_EMAIL") ?? "";
  const deletionPage = url.searchParams.get("action")?.toLowerCase() === "delete";
  const contact = supportEmail
    ? `<p><strong>${language === "ar" ? "التواصل" : "Contact"}:</strong> <a href="mailto:${supportEmail}">${supportEmail}</a></p>`
    : "";
  const deletion = deletionPage
    ? supportEmail
      ? `<section><h2>${language === "ar" ? "طلب حذف الحساب" : "Request account deletion"}</h2><p>${language === "ar" ? "يمكنك حذف حسابك مباشرة من داخل اللعبة عبر الإعدادات ← الحساب والخصوصية. إذا تعذر الوصول إلى اللعبة، أرسل طلبًا من بريد الحساب المسجل وسنرسل تعليمات التحقق قبل الحذف النهائي." : "You can delete your account directly in the game under Settings → Account & Privacy. If you cannot access the game, email us from the address registered to the account and we will send verification instructions before permanent deletion."}</p><p><a class="button" href="mailto:${supportEmail}?subject=FSP%20Account%20Deletion">${language === "ar" ? "إرسال طلب الحذف" : "Send deletion request"}</a></p></section>`
      : `<section><h2>${language === "ar" ? "طلب حذف الحساب" : "Request account deletion"}</h2><p>${language === "ar" ? "استخدم الإعدادات ← الحساب والخصوصية داخل اللعبة لطلب الحذف." : "Use Settings → Account & Privacy inside the game to request deletion."}</p></section>`
    : `<p><a href="?action=delete&lang=${language}">${language === "ar" ? "طلب حذف الحساب" : "Request account deletion"}</a></p>`;
  const direction = language === "ar" ? "rtl" : "ltr";
  const html = `<!doctype html><html lang="${language}" dir="${direction}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${content.title}</title><style>body{margin:0;background:#07111b;color:#f4f1e9;font:18px system-ui,sans-serif;line-height:1.8}.card{max-width:820px;margin:40px auto;padding:32px;background:#0d2233;border:1px solid #ff6500;border-radius:18px}h1,h2{color:#ff6500}h2{font-size:1.25em;margin-top:1.5em}a{color:#ff9a52}.button{display:inline-block;background:#ff6500;color:#07111b;padding:10px 18px;border-radius:10px;text-decoration:none;font-weight:700}.date{opacity:.75;font-size:14px}@media(max-width:640px){.card{margin:0;border-radius:0;padding:22px}}</style></head><body><main class="card"><h1>${content.title}</h1><p class="date">${language === "ar" ? "آخر تحديث: 20 أغسطس 2026" : "Last updated: 20 August 2026"}</p><p>${content.summary}</p>${content.details}${deletion}${contact}</main></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=3600" } });
});
