using Fsp.Inventory;
using UnityEngine;
namespace Fsp.World{
public sealed class LanternCoastPrototype:MonoBehaviour{
 Material sand,stone,wood,navy,bronze,water;
 void Start()=>Build();
 void Build(){if(transform.Find("GeneratedLanternCoast")!=null)return;var r=new GameObject("GeneratedLanternCoast").transform;r.SetParent(transform,false);r.localPosition=new Vector3(-155,0,105);sand=Mat(new Color(.62f,.52f,.37f));stone=Mat(new Color(.55f,.50f,.41f));wood=Mat(new Color(.32f,.22f,.14f));navy=Mat(new Color(.10f,.16f,.20f));bronze=Mat(new Color(.55f,.31f,.13f));water=Mat(new Color(.20f,.43f,.52f));Block(r,"CoastGround",new Vector3(0,-.2f,0),new Vector3(135,.4f,95),sand,true);Block(r,"Sea",new Vector3(-62,-.45f,0),new Vector3(45,.25f,110),water,false);BuildVillage(r);BuildPier(r);BuildLighthouse(r);BuildBoats(r);BuildRocks(r);BuildClimbPaths(r);SpawnLoot(r);}
 void BuildVillage(Transform r){for(int i=0;i<14;i++){var h=new GameObject("CoastHouse").transform;h.SetParent(r,false);float x=-25+(i%4)*18;float z=-34+(i/4)*19;float y=(i/4)*1.15f;h.localPosition=new Vector3(x,y,z);float w=7+(i%3);float d=6+(i%2)*2;Block(h,"Body",new Vector3(0,1.5f,0),new Vector3(w,3,d),i%3==0?navy:stone,true);Block(h,"Roof",new Vector3(0,3.2f,0),new Vector3(w+.7f,.3f,d+.7f),i%2==0?bronze:wood,true);Block(h,"DoorL",new Vector3(-w*.28f,1.1f,d*.52f),new Vector3(w*.32f,2.2f,.25f),stone,true);Block(h,"DoorR",new Vector3(w*.28f,1.1f,d*.52f),new Vector3(w*.32f,2.2f,.25f),stone,true);Block(h,"RoofCover",new Vector3(0,3.65f,-d*.25f),new Vector3(w*.6f,.7f,.5f),wood,true);}}
 void BuildPier(Transform r){for(int i=0;i<11;i++){Block(r,"PierDeck",new Vector3(-42-i*3.2f,.45f,18),new Vector3(3.4f,.3f,7),wood,true);for(int z=-1;z<=1;z+=2)Block(r,"PierPost",new Vector3(-42-i*3.2f,-.5f,18+z*2.7f),new Vector3(.35f,2,.35f),wood,true);}Block(r,"DockCrates",new Vector3(-50,1.1f,15),new Vector3(4,2.2f,3),bronze,true);}
 void BuildLighthouse(Transform r){var l=new GameObject("LanternLighthouse").transform;l.SetParent(r,false);l.localPosition=new Vector3(34,0,28);for(int i=0;i<6;i++){var c=GameObject.CreatePrimitive(PrimitiveType.Cylinder);c.name="TowerSection";c.transform.SetParent(l,false);c.transform.localPosition=new Vector3(0,1.5f+i*2.7f,0);float s=3.5f-i*.28f;c.transform.localScale=new Vector3(s,1.35f,s);var rr=c.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=i%2==0?stone:navy;}Block(l,"LanternDeck",new Vector3(0,17.3f,0),new Vector3(8,.35f,8),wood,true);var lamp=GameObject.CreatePrimitive(PrimitiveType.Cylinder);lamp.name="LanternRoom";lamp.transform.SetParent(l,false);lamp.transform.localPosition=new Vector3(0,19,0);lamp.transform.localScale=new Vector3(2.5f,1.5f,2.5f);var lr=lamp.GetComponent<Renderer>();if(lr!=null)lr.sharedMaterial=bronze;for(int i=0;i<22;i++)Block(l,"LighthouseStep",new Vector3(-4.1f,.35f+i*.72f,-3.5f+i*.28f),new Vector3(1.4f,.22f,.65f),wood,true);}
 void BuildBoats(Transform r){for(int i=0;i<5;i++){var b=new GameObject("FishingBoat").transform;b.SetParent(r,false);b.localPosition=new Vector3(-62-i*8,.05f,-20+i*12);b.localRotation=Quaternion.Euler(0,15+i*21,0);Block(b,"Hull",Vector3.zero,new Vector3(7,1.1f,2.5f),navy,true);Block(b,"Cab",new Vector3(1.2f,1.1f,0),new Vector3(2.4f,1.5f,2),stone,true);}}
 void BuildRocks(Transform r){for(int i=0;i<28;i++){var g=GameObject.CreatePrimitive(i%2==0?PrimitiveType.Sphere:PrimitiveType.Cube);g.name="CoastalRock";g.transform.SetParent(r,false);g.transform.localPosition=new Vector3(-48+(i*13)%92,.7f,-42+(i*23)%84);g.transform.localRotation=Quaternion.Euler(i*9,i*27,i*5);float s=1.2f+(i%5)*.45f;g.transform.localScale=new Vector3(s*1.5f,s,s);var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=stone;}}
 void BuildClimbPaths(Transform r){for(int i=0;i<12;i++)Block(r,"CoastStep",new Vector3(18+i*1.2f,.2f+i*.35f,10+i*.9f),new Vector3(2.2f,.25f,1.2f),stone,true);}
 void SpawnLoot(Transform r){for(int i=0;i<16;i++){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=$"coast_loot_{i}";g.transform.SetParent(r,false);g.transform.localPosition=new Vector3(-42+(i*17)%88,.5f,-35+(i*29)%74);g.transform.localScale=Vector3.one*.4f;var it=ScriptableObject.CreateInstance<InventoryItem>();it.hideFlags=HideFlags.DontSave;it.itemId=g.name;it.type=i%5==0?InventoryItemType.Medkit:i%5==1?InventoryItemType.Armor:InventoryItemType.Ammo;it.displayName=it.type.ToString();it.ammoAmount=it.type==InventoryItemType.Ammo?45:0;it.armorAmount=it.type==InventoryItemType.Armor?30:0;g.AddComponent<LootPickup>().Configure(it,g.name,true);}}
 static GameObject Block(Transform p,string n,Vector3 pos,Vector3 scale,Material m,bool col){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=m;if(!col){var c=g.GetComponent<Collider>();if(c!=null)Destroy(c);}return g;}static Material Mat(Color c){var s=Shader.Find("Standard");var m=new Material(s!=null?s:Shader.Find("Sprites/Default"));m.color=c;return m;}
}}
