using Fsp.Inventory;
using UnityEngine;
namespace Fsp.World
{
 public sealed class SaltworksPrototype:MonoBehaviour
 {
  Material salt,water,metal,rust,pipe;
  void Start()=>Build();
  void Build(){if(transform.Find("GeneratedSaltworks")!=null)return;var r=new GameObject("GeneratedSaltworks").transform;r.SetParent(transform,false);r.localPosition=new Vector3(-15,0,165);salt=Mat(new Color(.82f,.79f,.69f));water=Mat(new Color(.36f,.55f,.58f));metal=Mat(new Color(.25f,.29f,.29f));rust=Mat(new Color(.48f,.25f,.14f));pipe=Mat(new Color(.32f,.34f,.32f));Block(r,"SaltGround",new Vector3(0,-.18f,0),new Vector3(145,.36f,105),salt,true);BuildPans(r);BuildPumpHouse(r);BuildPipeRuns(r);BuildWalkways(r);BuildSaltPiles(r);SpawnLoot(r);}
  void BuildPans(Transform r){for(int x=-1;x<=1;x++)for(int z=-1;z<=1;z++){if(x==0&&z==0)continue;Block(r,"BrinePan",new Vector3(x*38,.04f,z*27),new Vector3(31,.12f,20),water,true);for(int s=-1;s<=1;s+=2){Block(r,"PanWall",new Vector3(x*38+s*16,.45f,z*27),new Vector3(.8f,.9f,22),salt,true);Block(r,"PanWall",new Vector3(x*38,.45f,z*27+s*10.5f),new Vector3(33,.9f,.8f),salt,true);}}}
  void BuildPumpHouse(Transform r){var p=new GameObject("PumpHouse").transform;p.SetParent(r,false);p.localPosition=new Vector3(0,0,0);Block(p,"Floor",new Vector3(0,.1f,0),new Vector3(20,.2f,14),metal,true);Block(p,"Back",new Vector3(0,3,-7),new Vector3(20,6,.35f),rust,true);Block(p,"Left",new Vector3(-10,3,0),new Vector3(.35f,6,14),rust,true);Block(p,"Right",new Vector3(10,3,0),new Vector3(.35f,6,14),rust,true);Block(p,"Roof",new Vector3(0,6,0),new Vector3(20.5f,.35f,14.5f),metal,true);for(int i=0;i<4;i++){var c=GameObject.CreatePrimitive(PrimitiveType.Cylinder);c.name="Pump";c.transform.SetParent(p,false);c.transform.localPosition=new Vector3(-6+i*4,1.2f,0);c.transform.localScale=new Vector3(1.4f,1.2f,1.4f);var rr=c.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=metal;}}
  void BuildPipeRuns(Transform r){for(int row=0;row<4;row++)for(int i=0;i<8;i++){var c=GameObject.CreatePrimitive(PrimitiveType.Cylinder);c.name="Pipe";c.transform.SetParent(r,false);c.transform.localPosition=new Vector3(-49+i*14,1.1f,-40+row*26);c.transform.localRotation=Quaternion.Euler(0,0,90);c.transform.localScale=new Vector3(.55f,6.5f,.55f);var rr=c.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=pipe;}for(int i=0;i<12;i++)Block(r,"PipeSupport",new Vector3(-55+i*10,.55f,-1),new Vector3(.45f,1.1f,2.8f),metal,true);}
  void BuildWalkways(Transform r){for(int i=-3;i<=3;i++)Block(r,"Walkway",new Vector3(i*18,1.8f,0),new Vector3(14,.25f,2.2f),metal,true);for(int i=0;i<9;i++)Block(r,"Step",new Vector3(-8+i*.85f,.2f+i*.2f,8),new Vector3(1.1f,.2f,2),metal,true);}
  void BuildSaltPiles(Transform r){for(int i=0;i<18;i++){var g=GameObject.CreatePrimitive(PrimitiveType.Sphere);g.name="SaltPile";g.transform.SetParent(r,false);g.transform.localPosition=new Vector3(-62+(i*17)%125,.8f,-43+(i*29)%86);g.transform.localScale=new Vector3(3+(i%4),1.2f+(i%3)*.5f,3+(i%4));var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=salt;}}
  void SpawnLoot(Transform r){for(int i=0;i<15;i++){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=$"saltworks_loot_{i}";g.transform.SetParent(r,false);g.transform.localPosition=new Vector3(-58+(i*19)%118,.5f,-40+(i*31)%82);g.transform.localScale=Vector3.one*.4f;var it=ScriptableObject.CreateInstance<InventoryItem>();it.hideFlags=HideFlags.DontSave;it.itemId=g.name;it.type=i%5==0?InventoryItemType.Medkit:i%5==1?InventoryItemType.Armor:InventoryItemType.Ammo;it.displayName=it.type.ToString();it.ammoAmount=it.type==InventoryItemType.Ammo?50:0;it.armorAmount=it.type==InventoryItemType.Armor?30:0;g.AddComponent<LootPickup>().Configure(it,g.name,true);}}
  static GameObject Block(Transform p,string n,Vector3 pos,Vector3 scale,Material m,bool col){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=m;if(!col){var c=g.GetComponent<Collider>();if(c!=null)Destroy(c);}return g;}static Material Mat(Color c){var s=Shader.Find("Standard");var m=new Material(s!=null?s:Shader.Find("Sprites/Default"));m.color=c;return m;}
 }
}
