using UnityEngine;
namespace Fsp.World{
public sealed class SunscarIslandPolish:MonoBehaviour{
 Material sand,rock,green,water,roadSign;
 void Start()=>Build();
 void Build(){if(transform.Find("GeneratedIslandPolish")!=null)return;var r=new GameObject("GeneratedIslandPolish").transform;r.SetParent(transform,false);sand=Mat(new Color(.48f,.40f,.28f));rock=Mat(new Color(.38f,.36f,.32f));green=Mat(new Color(.24f,.31f,.20f));water=Mat(new Color(.16f,.38f,.48f));roadSign=Mat(new Color(.10f,.16f,.20f));
 Block(r,"IslandBase",new Vector3(0,-2.2f,10),new Vector3(410,4,410),sand,true);BuildSea(r);BuildRidges(r);BuildNature(r);BuildSigns(r);}
 void BuildSea(Transform r){Block(r,"OceanNorth",new Vector3(0,-1.1f,250),new Vector3(620,.4f,170),water,false);Block(r,"OceanSouth",new Vector3(0,-1.1f,-240),new Vector3(620,.4f,170),water,false);Block(r,"OceanEast",new Vector3(250,-1.1f,5),new Vector3(170,.4f,330),water,false);Block(r,"OceanWest",new Vector3(-250,-1.1f,5),new Vector3(170,.4f,330),water,false);}
 void BuildRidges(Transform r){for(int i=0;i<32;i++){var g=GameObject.CreatePrimitive(PrimitiveType.Sphere);g.name="TerrainRidge";g.transform.SetParent(r,false);float a=i/32f*Mathf.PI*2;float rad=185+(i%4)*5;g.transform.localPosition=new Vector3(Mathf.Cos(a)*rad,-.6f,Mathf.Sin(a)*rad+8);g.transform.localScale=new Vector3(22+(i%5)*4,4+(i%3)*2,16+(i%4)*3);var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=i%3==0?rock:sand;}}
 void BuildNature(Transform r){for(int i=0;i<85;i++){float x=-175+(i*47)%350;float z=-170+(i*73)%350;if(Mathf.Abs(x)<20&&Mathf.Abs(z)<20)continue;if(i%3==0){var trunk=Block(r,"TreeTrunk",new Vector3(x,1.5f,z),new Vector3(.45f,3,.45f),rock,true);var crown=GameObject.CreatePrimitive(PrimitiveType.Sphere);crown.name="TreeCrown";crown.transform.SetParent(r,false);crown.transform.localPosition=new Vector3(x,3.7f,z);crown.transform.localScale=new Vector3(2.7f,2.2f,2.7f);var rr=crown.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=green;}else{var g=GameObject.CreatePrimitive(PrimitiveType.Sphere);g.name="WorldRock";g.transform.SetParent(r,false);g.transform.localPosition=new Vector3(x,.6f,z);float s=.8f+(i%5)*.3f;g.transform.localScale=new Vector3(s*1.4f,s,s);var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=rock;}}}
 void BuildSigns(Transform r){Sign(r,"OLD CROWN",new Vector3(-76,1.7f,18),25);Sign(r,"COPPER PORT",new Vector3(55,1.7f,-35),-20);Sign(r,"DRYFIELD",new Vector3(82,1.7f,76),15);Sign(r,"WHITE QUARRY",new Vector3(-104,1.7f,-63),35);Sign(r,"REDLINE",new Vector3(127,1.7f,-98),-25);Sign(r,"SALTWORKS",new Vector3(-10,1.7f,138),10);Sign(r,"LANTERN COAST",new Vector3(-130,1.7f,86),30);}
 void Sign(Transform r,string name,Vector3 p,float yaw){var root=new GameObject("Sign_"+name).transform;root.SetParent(r,false);root.localPosition=p;root.localRotation=Quaternion.Euler(0,yaw,0);Block(root,"PostL",new Vector3(-1.5f,-.2f,0),new Vector3(.18f,2.7f,.18f),rock,true);Block(root,"PostR",new Vector3(1.5f,-.2f,0),new Vector3(.18f,2.7f,.18f),rock,true);Block(root,name,new Vector3(0,.8f,0),new Vector3(4.2f,1.25f,.2f),roadSign,true);}
 static GameObject Block(Transform p,string n,Vector3 pos,Vector3 scale,Material m,bool col){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;var rr=g.GetComponent<Renderer>();if(rr!=null)rr.sharedMaterial=m;if(!col){var c=g.GetComponent<Collider>();if(c!=null)Destroy(c);}return g;}static Material Mat(Color c){var s=Shader.Find("Standard");var m=new Material(s!=null?s:Shader.Find("Sprites/Default"));m.color=c;return m;}
}}
